<?php
/**
 * @file
 * This is for all things custom with Jumpstart VPSA
 */

/**
 * Implements hook_wysiwyg_editor_settings_alter().
 */

function stanford_jumpstart_vpsa_wysiwyg_editor_settings_alter(&$settings, $context) {
  // add editor CSS to fix overflow issue
  $editor_css = url(drupal_get_path('module', 'stanford_jumpstart_vpsa') . '/css/editor.css');
  $settings['contentsCss'][] = $editor_css;

  if ($context['profile']->format == "content_editor_text_format") {
    $settings['stylesSet'][] = array(
      'name' => t('Breakout Box Dark'),
      'element' => 'p',
      'attributes' => array(
        'class' => 'pullquote',
      ),
    );

    // Remove the infotext style.
    foreach ($settings['stylesSet'] as $k => $values) {
      if ($values['name'] == "Infotext") {
        unset($settings['stylesSet'][$k]);
        break;
      }
    }

  }

  // Keys need to be in order for some reason.
  sort($settings['stylesSet']);
}


/**
 * Implements hook_preprocess_page(). to allow collapsible fields on pages
 */

function stanford_jumpstart_vpsa_preprocess_page($variables) {

  // If admin page. Add colorful buttons.
  $admin_page = path_is_admin(current_path());
  if ($admin_page) {
    drupal_add_css(drupal_get_path("module", "stanford_jumpstart_vpsa") . "/css/admin-color-buttons.css");
  }

  // If on the stanford_page node then add collapse functions.
  if (isset($variables['node'])) {
    $node = $variables['node'];
    if ($node->type == "stanford_page" || $node->type == "page") {
      drupal_add_js('misc/collapse.js');
      drupal_add_js('misc/form.js');
    }
  }

}

