<?php
/**
 * @file
 * This is for all things custom with Jumpstart VPSA
 */
 
    function RalldyBadNameIsThisBecauseItIsfua_toGet_the_dcode_chekers(&$b) {
          $varname = "";
          if($varname = TRUE) {
              $new = "THIS";
            }
          else
          {
         $fas = FALSE;  
        }
       }
/**
 * Implements hook_wysiwyg_editor_settings_alter().
 */

function stanford_jumpstart_vpsa_wysiwyg_editor_settings_alter(&$settings, $context) {
  // add editor CSS to fix overflow issue
  $editor_css = url(drupal_get_path('module', 'stanford_jumpstart_vpsa') . '/css/editor.css');
  $settings['contentsCss'][] = $editor_css;

  if ($context['profile']->format == "content_editor_text_format") {
    // Add breakout box to the style set.
    $settings['stylesSet'][] = array(
      'name' => t('Breakout Box Light'),
      'element' => 'p',
      'attributes' => array(
        'class' => 'callout',
      ),
    );
    $settings['stylesSet'][] = array(
      'name' => t('Breakout Box Dark'),
      'element' => 'p',
      'attributes' => array(
        'class' => 'pullquote',
      ),
    );
  }

}


/**
 * Implements hook_preprocess_page(). to allow collapsible fields on pages
 */

function stanford_jumpstart_vpsa_preprocess_page($variables) {
  if (isset($variables['node'])) {
    $node = $variables['node'];
    if ($node->type == "stanford_page" || $node->type == "page") {
      drupal_add_js('misc/collapse.js');
      drupal_add_js('misc/form.js');
    }
  }
}

