<?php
/**
 * @file
 * Code for the Stanford Jumpstart VPSA Layouts feature.
 */

include_once 'stanford_jumpstart_vpsa_shortcuts.features.inc';

/**
 * Implements hook_block_info().
 */
function stanford_jumpstart_vpsa_shortcuts_block_info() {
  $blocks['hello']['info'] = t('Jumpstart Hello "User" Block');
  $blocks['hello']['cache'] = DRUPAL_CACHE_PER_USER;
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function stanford_jumpstart_vpsa_shortcuts_block_view($delta = '') {
  $block = array();
  switch($delta) {
    case 'hello':
      global $user;
      $content = '<div class="shortcuts-user">';
      $content .= t('Hello, !name', array('!name' => l($user->name, 'user/' . $user->uid . '/edit')));
      $content .= '</div><div class="shortcuts-logout">';
      $content .= t(l('Log out', 'user/logout'));
      $content .= '</div>';
      $block['subject'] = NULL;
      $block['content'] = $content;
    break;
  }
  return $block;
}

/**
 * Implements hook_permission().
 */
function stanford_jumpstart_vpsa_shortcuts_permission() {
  return array(
    'stanford jumpstart clear caches' => array(
      'title' => t('Clear Site Caches'),
      'description' => t('Provide access to the "refresh site content" (clear all caches) shortcut item.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function stanford_jumpstart_vpsa_shortcuts_menu() {
  $items['admin/stanford/jumpstart/shortcuts/clear-cache'] = array(
    'title' => 'Refresh Site Content',
    'page callback' => 'stanford_jumpstart_vpsa_shortcuts_clear_all_caches',
    'access arguments' => array('stanford jumpstart clear caches'),
    'options' => array(
      'query' => array(
        'destination' => current_path(),
      ),
      'attributes' => array(
        'class' => 'su-clear-cache',
        'title' => 'Refresh Site Content',
      ),
    ),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function stanford_jumpstart_preprocess_link(&$vars) {
  // Schtoopid features stores things I don't want it to.
  if ($vars['path'] == 'admin/stanford/jumpstart/shortcuts/clear-cache') {
    $vars['options']['query'] = drupal_get_destination();
  }
}

/**
 * Clears all caches and returns the user to the destination page
 */
function stanford_jumpstart_vpsa_shortcuts_clear_all_caches() {
  drupal_flush_all_caches();
  drupal_set_message('Site Content Refreshed.');

  $destination = drupal_get_destination();
  if ($destination['destination'] == current_path()) {
    $destination['destination'] = "admin/content";
  }

  drupal_goto($destination['destination']);
}
